-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.audit_logs
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid NOT NULL,
    entity_type character varying(80) COLLATE pg_catalog."default" NOT NULL,
    entity_id uuid NOT NULL,
    action character varying(40) COLLATE pg_catalog."default" NOT NULL,
    field_name character varying(100) COLLATE pg_catalog."default",
    old_value text COLLATE pg_catalog."default",
    new_value text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.brands
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying(120) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(80) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT brands_pkey PRIMARY KEY (id),
    CONSTRAINT brands_name_key UNIQUE (name),
    CONSTRAINT brands_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.media_files
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    message_id uuid NOT NULL,
    media_type character varying(30) COLLATE pg_catalog."default",
    original_url text COLLATE pg_catalog."default",
    storage_key character varying(500) COLLATE pg_catalog."default",
    storage_bucket character varying(100) COLLATE pg_catalog."default",
    mime_type character varying(100) COLLATE pg_catalog."default",
    file_size bigint,
    ai_description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT media_files_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.merchandiser_report_item_batches
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    report_item_id uuid NOT NULL,
    quantity integer,
    expiry_date date,
    expiry_raw character varying(50) COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT merchandiser_report_item_batches_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.merchandiser_report_items
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    merchandiser_report_id uuid NOT NULL,
    product_id uuid,
    product_name_raw character varying(300) COLLATE pg_catalog."default" NOT NULL,
    quantity integer,
    expiry_date date,
    expiry_raw character varying(50) COLLATE pg_catalog."default",
    is_product_matched boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    match_confidence numeric(4, 3),
    match_type character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT merchandiser_report_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.merchandiser_reports
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    report_id uuid NOT NULL,
    promo_type character varying(100) COLLATE pg_catalog."default",
    notes text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT merchandiser_reports_pkey PRIMARY KEY (id),
    CONSTRAINT merchandiser_reports_report_id_key UNIQUE (report_id)
);

CREATE TABLE IF NOT EXISTS public.outlets
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    type outlet_type NOT NULL DEFAULT 'supermarket'::outlet_type,
    is_depot boolean NOT NULL DEFAULT false,
    region_id uuid,
    address text COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT outlets_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.parsed_reports
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    message_id uuid NOT NULL,
    brand_id uuid,
    outlet_id uuid,
    reported_by uuid,
    report_date date,
    report_type report_type NOT NULL,
    status parsed_report_status NOT NULL DEFAULT 'draft'::parsed_report_status,
    confidence numeric(4, 3),
    location_raw text COLLATE pg_catalog."default",
    date_raw character varying(100) COLLATE pg_catalog."default",
    name_raw character varying(150) COLLATE pg_catalog."default",
    is_depot_report boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT parsed_reports_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_aliases
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    product_id uuid NOT NULL,
    alias character varying(200) COLLATE pg_catalog."default" NOT NULL,
    created_by uuid,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT product_aliases_pkey PRIMARY KEY (id),
    CONSTRAINT product_aliases_alias_key UNIQUE (alias)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    brand_id uuid NOT NULL,
    canonical_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    sku character varying(80) COLLATE pg_catalog."default",
    flow product_flow NOT NULL DEFAULT 'both'::product_flow,
    unit character varying(30) COLLATE pg_catalog."default",
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    sort_order integer NOT NULL DEFAULT 0,
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT products_brand_id_canonical_name_key UNIQUE (brand_id, canonical_name)
);

CREATE TABLE IF NOT EXISTS public.promoter_reports
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    report_id uuid NOT NULL,
    promo_stand_placement text COLLATE pg_catalog."default",
    persons_contacted integer,
    persons_tasted integer,
    feedback_text text COLLATE pg_catalog."default",
    most_asked_question text COLLATE pg_catalog."default",
    questions_answers jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT promoter_reports_pkey PRIMARY KEY (id),
    CONSTRAINT promoter_reports_report_id_key UNIQUE (report_id)
);

CREATE TABLE IF NOT EXISTS public.promoter_sale_items
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    promoter_report_id uuid NOT NULL,
    product_id uuid,
    product_name_raw character varying(300) COLLATE pg_catalog."default" NOT NULL,
    quantity integer,
    promo_label character varying(150) COLLATE pg_catalog."default",
    is_offer boolean NOT NULL DEFAULT false,
    is_product_matched boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    match_confidence numeric(4, 3),
    match_type character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT promoter_sale_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.promoter_sample_items
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    promoter_report_id uuid NOT NULL,
    product_id uuid,
    product_name_raw character varying(300) COLLATE pg_catalog."default" NOT NULL,
    quantity integer,
    availability_note character varying(150) COLLATE pg_catalog."default",
    is_product_matched boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    match_confidence numeric(4, 3),
    match_type character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT promoter_sample_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.regions
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    country character varying(60) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Lebanon'::character varying,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT regions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.report_flags
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    report_id uuid NOT NULL,
    flag_code character varying(80) COLLATE pg_catalog."default" NOT NULL,
    field_name character varying(100) COLLATE pg_catalog."default",
    severity flag_severity NOT NULL DEFAULT 'warning'::flag_severity,
    message text COLLATE pg_catalog."default",
    status flag_status NOT NULL DEFAULT 'open'::flag_status,
    resolved_by uuid,
    resolved_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT report_flags_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.unknown_senders
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    sender_phone character varying(30) COLLATE pg_catalog."default" NOT NULL,
    sender_name character varying(150) COLLATE pg_catalog."default",
    seen_count integer NOT NULL DEFAULT 1,
    first_seen_at timestamp with time zone NOT NULL DEFAULT now(),
    last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
    resolved_brand_id uuid,
    resolved_at timestamp with time zone,
    CONSTRAINT unknown_senders_pkey PRIMARY KEY (id),
    CONSTRAINT unknown_senders_sender_phone_key UNIQUE (sender_phone)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    full_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    whatsapp_phone character varying(30) COLLATE pg_catalog."default",
    email character varying(150) COLLATE pg_catalog."default",
    password_hash character varying(255) COLLATE pg_catalog."default",
    role user_role NOT NULL DEFAULT 'reviewer'::user_role,
    brand_id uuid,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_whatsapp_phone_key UNIQUE (whatsapp_phone)
);

CREATE TABLE IF NOT EXISTS public.whatsapp_messages
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    wa_message_id character varying(200) COLLATE pg_catalog."default" NOT NULL,
    sender_phone character varying(30) COLLATE pg_catalog."default",
    sender_name character varying(150) COLLATE pg_catalog."default",
    body_raw text COLLATE pg_catalog."default",
    body_normalized text COLLATE pg_catalog."default",
    message_type character varying(30) COLLATE pg_catalog."default",
    has_media boolean NOT NULL DEFAULT false,
    report_type report_type,
    status message_status NOT NULL DEFAULT 'received'::message_status,
    ai_classification jsonb,
    ai_extraction jsonb,
    ai_confidence numeric(4, 3),
    received_at timestamp with time zone NOT NULL,
    processed_at timestamp with time zone,
    reviewed_by uuid,
    reviewed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT whatsapp_messages_pkey PRIMARY KEY (id),
    CONSTRAINT whatsapp_messages_wa_message_id_key UNIQUE (wa_message_id)
);

ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id
    ON public.audit_logs(user_id);


ALTER TABLE IF EXISTS public.media_files
    ADD CONSTRAINT media_files_message_id_fkey FOREIGN KEY (message_id)
    REFERENCES public.whatsapp_messages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_media_files_message_id
    ON public.media_files(message_id);


ALTER TABLE IF EXISTS public.merchandiser_report_item_batches
    ADD CONSTRAINT merchandiser_report_item_batches_report_item_id_fkey FOREIGN KEY (report_item_id)
    REFERENCES public.merchandiser_report_items (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_item_batches_report_item_id
    ON public.merchandiser_report_item_batches(report_item_id);


ALTER TABLE IF EXISTS public.merchandiser_report_items
    ADD CONSTRAINT merchandiser_report_items_merchandiser_report_id_fkey FOREIGN KEY (merchandiser_report_id)
    REFERENCES public.merchandiser_reports (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_merch_items_merchandiser_report_id
    ON public.merchandiser_report_items(merchandiser_report_id);


ALTER TABLE IF EXISTS public.merchandiser_report_items
    ADD CONSTRAINT merchandiser_report_items_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_merch_items_product_id
    ON public.merchandiser_report_items(product_id);


ALTER TABLE IF EXISTS public.merchandiser_reports
    ADD CONSTRAINT merchandiser_reports_report_id_fkey FOREIGN KEY (report_id)
    REFERENCES public.parsed_reports (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS merchandiser_reports_report_id_key
    ON public.merchandiser_reports(report_id);


ALTER TABLE IF EXISTS public.outlets
    ADD CONSTRAINT outlets_region_id_fkey FOREIGN KEY (region_id)
    REFERENCES public.regions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.parsed_reports
    ADD CONSTRAINT parsed_reports_brand_id_fkey FOREIGN KEY (brand_id)
    REFERENCES public.brands (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_parsed_reports_brand_id
    ON public.parsed_reports(brand_id);


ALTER TABLE IF EXISTS public.parsed_reports
    ADD CONSTRAINT parsed_reports_message_id_fkey FOREIGN KEY (message_id)
    REFERENCES public.whatsapp_messages (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_parsed_reports_message_id
    ON public.parsed_reports(message_id);


ALTER TABLE IF EXISTS public.parsed_reports
    ADD CONSTRAINT parsed_reports_outlet_id_fkey FOREIGN KEY (outlet_id)
    REFERENCES public.outlets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_parsed_reports_outlet_id
    ON public.parsed_reports(outlet_id);


ALTER TABLE IF EXISTS public.parsed_reports
    ADD CONSTRAINT parsed_reports_reported_by_fkey FOREIGN KEY (reported_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_parsed_reports_reported_by
    ON public.parsed_reports(reported_by);


ALTER TABLE IF EXISTS public.product_aliases
    ADD CONSTRAINT product_aliases_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product_aliases
    ADD CONSTRAINT product_aliases_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_product_aliases_product_id
    ON public.product_aliases(product_id);


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT products_brand_id_fkey FOREIGN KEY (brand_id)
    REFERENCES public.brands (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_products_brand_id
    ON public.products(brand_id);


ALTER TABLE IF EXISTS public.promoter_reports
    ADD CONSTRAINT promoter_reports_report_id_fkey FOREIGN KEY (report_id)
    REFERENCES public.parsed_reports (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS promoter_reports_report_id_key
    ON public.promoter_reports(report_id);


ALTER TABLE IF EXISTS public.promoter_sale_items
    ADD CONSTRAINT promoter_sale_items_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_sale_items_product_id
    ON public.promoter_sale_items(product_id);


ALTER TABLE IF EXISTS public.promoter_sale_items
    ADD CONSTRAINT promoter_sale_items_promoter_report_id_fkey FOREIGN KEY (promoter_report_id)
    REFERENCES public.promoter_reports (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_sale_items_promoter_report_id
    ON public.promoter_sale_items(promoter_report_id);


ALTER TABLE IF EXISTS public.promoter_sample_items
    ADD CONSTRAINT promoter_sample_items_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_sample_items_product_id
    ON public.promoter_sample_items(product_id);


ALTER TABLE IF EXISTS public.promoter_sample_items
    ADD CONSTRAINT promoter_sample_items_promoter_report_id_fkey FOREIGN KEY (promoter_report_id)
    REFERENCES public.promoter_reports (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_sample_items_promoter_report_id
    ON public.promoter_sample_items(promoter_report_id);


ALTER TABLE IF EXISTS public.report_flags
    ADD CONSTRAINT report_flags_report_id_fkey FOREIGN KEY (report_id)
    REFERENCES public.parsed_reports (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_report_flags_report_id
    ON public.report_flags(report_id);


ALTER TABLE IF EXISTS public.report_flags
    ADD CONSTRAINT report_flags_resolved_by_fkey FOREIGN KEY (resolved_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.unknown_senders
    ADD CONSTRAINT unknown_senders_resolved_brand_id_fkey FOREIGN KEY (resolved_brand_id)
    REFERENCES public.brands (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_brand_id_fkey FOREIGN KEY (brand_id)
    REFERENCES public.brands (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_users_brand_id
    ON public.users(brand_id);


ALTER TABLE IF EXISTS public.whatsapp_messages
    ADD CONSTRAINT whatsapp_messages_reviewed_by_fkey FOREIGN KEY (reviewed_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;